// flow-typed signature: e764c5ad6690df4441d36f4edd6e2046
// flow-typed version: <<STUB>>/mongodb-prebuilt_v^6.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-prebuilt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-prebuilt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb-prebuilt/built/bin/bsondump' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongo-supervise' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongo' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongod' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongodump' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongoexport' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongofiles' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongoimport' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongooplog' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongoperf' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongorestore' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongos' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongosniff' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongostat' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/bin/mongotop' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/mongo-bins' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/mongod-helper' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/mongodb-prebuilt-all' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/mongodb-prebuilt' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/built/mongodb-supervise' {
  declare module.exports: any;
}

declare module 'mongodb-prebuilt/helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb-prebuilt/built/bin/bsondump.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/bsondump'>;
}
declare module 'mongodb-prebuilt/built/bin/mongo-supervise.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongo-supervise'>;
}
declare module 'mongodb-prebuilt/built/bin/mongo.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongo'>;
}
declare module 'mongodb-prebuilt/built/bin/mongod.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongod'>;
}
declare module 'mongodb-prebuilt/built/bin/mongodump.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongodump'>;
}
declare module 'mongodb-prebuilt/built/bin/mongoexport.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongoexport'>;
}
declare module 'mongodb-prebuilt/built/bin/mongofiles.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongofiles'>;
}
declare module 'mongodb-prebuilt/built/bin/mongoimport.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongoimport'>;
}
declare module 'mongodb-prebuilt/built/bin/mongooplog.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongooplog'>;
}
declare module 'mongodb-prebuilt/built/bin/mongoperf.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongoperf'>;
}
declare module 'mongodb-prebuilt/built/bin/mongorestore.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongorestore'>;
}
declare module 'mongodb-prebuilt/built/bin/mongos.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongos'>;
}
declare module 'mongodb-prebuilt/built/bin/mongosniff.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongosniff'>;
}
declare module 'mongodb-prebuilt/built/bin/mongostat.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongostat'>;
}
declare module 'mongodb-prebuilt/built/bin/mongotop.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/bin/mongotop'>;
}
declare module 'mongodb-prebuilt/built/mongo-bins.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/mongo-bins'>;
}
declare module 'mongodb-prebuilt/built/mongod-helper.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/mongod-helper'>;
}
declare module 'mongodb-prebuilt/built/mongodb-prebuilt-all.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/mongodb-prebuilt-all'>;
}
declare module 'mongodb-prebuilt/built/mongodb-prebuilt.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/mongodb-prebuilt'>;
}
declare module 'mongodb-prebuilt/built/mongodb-supervise.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/built/mongodb-supervise'>;
}
declare module 'mongodb-prebuilt/helper.js' {
  declare module.exports: $Exports<'mongodb-prebuilt/helper'>;
}
