// flow-typed signature: 4afebfe8b27973c18cd40ad5dc9324fb
// flow-typed version: <<STUB>>/semantic-release_v^6.3.6/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-release/bin/semantic-release' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/commits' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/get-registry' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/plugin-noop' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/plugins' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/type' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/verify' {
  declare module.exports: any;
}

declare module 'semantic-release/src/post' {
  declare module.exports: any;
}

declare module 'semantic-release/src/pre' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-release/bin/semantic-release.js' {
  declare module.exports: $Exports<'semantic-release/bin/semantic-release'>;
}
declare module 'semantic-release/src/lib/commits.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/commits'>;
}
declare module 'semantic-release/src/lib/get-registry.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/get-registry'>;
}
declare module 'semantic-release/src/lib/plugin-noop.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/plugin-noop'>;
}
declare module 'semantic-release/src/lib/plugins.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/plugins'>;
}
declare module 'semantic-release/src/lib/type.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/type'>;
}
declare module 'semantic-release/src/lib/verify.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/verify'>;
}
declare module 'semantic-release/src/post.js' {
  declare module.exports: $Exports<'semantic-release/src/post'>;
}
declare module 'semantic-release/src/pre.js' {
  declare module.exports: $Exports<'semantic-release/src/pre'>;
}
